### PR TITLE
#22-createFirebaseUser-method

### PR DESCRIPTION
**Pull request by Leila-Bel**
Created a firebase helper class and added a create user method/ edited the code in registration activity.

### CODE REVIEW

**Review by ckareez — COMMENTED** [review]
Looks good! just make sure after registration it goes to login activity

**Comment by Leila-Bel** [comment]
@maxb6  we have an issue with your OnComplete functions and we don't know how to move past it. When we run the code what happens after the OnComplete runs before the OnComplete and we don't know how to fix that.

**Comment by Leila-Bel** [comment]
@maxb6 nevermindddddd

**Comment by Leila-Bel** [comment]
do not add this to master. we'll be changing some stuff

**Pull request closed without merging**
